name: C++ CI

on:
  push:
    branches:
      - ak5k-patch-1
    # tags:
    #   - '*'


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cpp_compiler: [g++, clang++]
        c_compiler: [gcc, clang]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some setup steps may vary depending on the operating system
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update
          sudo apt-get install -y cmake
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install cmake
        fi

    - name: Configure CMake
      # Note the current configuration is for a basic C++ project. You'll need to update this for your specific needs.
      run: cmake -B ${{ github.workspace }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{ github.workspace }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ github.workspace }}
      # Execute tests defined by the CMake configuration
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false